2021-07-09 04:13:58.151191 >>> {command: get_health}
2021-07-09 04:13:59.322712 <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:13:59.433713 >>> {command: request_data, timeout: 1200000}
2021-07-09 04:14:04.881023 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"full app test\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following StateError was thrown running a test:\\nBad state: No element\\n\\nWhen the exception was thrown, this was the stack:\\n#0      Iterable.first (dart:core/iterable.dart:490:7)\\n#1      _FirstFinder.filter (package:flutter_test/src/finders.dart:477:28)\\n#2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)\\n#3      ExpandIterator.moveNext (dart:_internal/iterable.dart:477:21)\\n#4      SetMixin.addAll (dart:collection/set.dart:57:23)\\n#5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:111:27)\\n#6      Iterable.toSet (dart:core/iterable.dart:398:21)\\n#7      _DescendantFinder.allCandidates (package:flutter_test/src/finders.dart:731:7)\\n#8      Finder.evaluate (package:flutter_test/src/finders.dart:391:61)\\n#9      WidgetController.state (package:flutter_test/src/controller.dart:156:31)\\n#10     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1027:42)\\n#11     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1026:39)\\n#14     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#15     WidgetTester.showKeyboard (package:flutter_test/src/widget_tester.dart:1026:27)\\n#16     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1062:13)\\n#17     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1061:39)\\n#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#21     WidgetTester.enterText (package:flutter_test/src/widget_tester.dart:1061:27)\\n#22     main.<anonymous closure>.<anonymous closure> (file:///D:/Master%20Folder/GSU/App%20Dev/demo8/GroupChatApp/integration_test/app_test.dart:16:20)\\n<asynchronous suspension>\\n#23     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:155:15)\\n<asynchronous suspension>\\n#24     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:782:5)\\n<asynchronous suspension>\\n(elided 4 frames from dart:async)\\n\\nThe test description was:\\n  full app test\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:17:27.553194 >>> {command: get_health}
2021-07-09 04:17:27.894195 <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:17:27.989193 >>> {command: request_data, timeout: 1200000}
2021-07-09 04:17:32.985406 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"full app test\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following StateError was thrown running a test:\\nBad state: No element\\n\\nWhen the exception was thrown, this was the stack:\\n#0      Iterable.first (dart:core/iterable.dart:490:7)\\n#1      _FirstFinder.filter (package:flutter_test/src/finders.dart:477:28)\\n#2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)\\n#3      ExpandIterator.moveNext (dart:_internal/iterable.dart:477:21)\\n#4      SetMixin.addAll (dart:collection/set.dart:57:23)\\n#5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:111:27)\\n#6      Iterable.toSet (dart:core/iterable.dart:398:21)\\n#7      _DescendantFinder.allCandidates (package:flutter_test/src/finders.dart:731:7)\\n#8      Finder.evaluate (package:flutter_test/src/finders.dart:391:61)\\n#9      WidgetController.state (package:flutter_test/src/controller.dart:156:31)\\n#10     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1027:42)\\n#11     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1026:39)\\n#14     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#15     WidgetTester.showKeyboard (package:flutter_test/src/widget_tester.dart:1026:27)\\n#16     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1062:13)\\n#17     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1061:39)\\n#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#21     WidgetTester.enterText (package:flutter_test/src/widget_tester.dart:1061:27)\\n#22     main.<anonymous closure>.<anonymous closure> (file:///D:/Master%20Folder/GSU/App%20Dev/demo8/GroupChatApp/integration_test/app_test.dart:16:20)\\n<asynchronous suspension>\\n#23     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:155:15)\\n<asynchronous suspension>\\n#24     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:782:5)\\n<asynchronous suspension>\\n(elided 4 frames from dart:async)\\n\\nThe test description was:\\n  full app test\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:19:13.910827 >>> {command: get_health}
2021-07-09 04:19:14.392826 <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:19:14.512825 >>> {command: request_data, timeout: 1200000}
2021-07-09 04:19:24.675637 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:28:01.228802 >>> {command: get_health}
2021-07-09 04:28:01.628354 <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:28:01.792347 >>> {command: request_data, timeout: 1200000}
2021-07-09 04:28:11.402100 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"full app test\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following StateError was thrown running a test:\\nBad state: No element\\n\\nWhen the exception was thrown, this was the stack:\\n#0      Iterable.first (dart:core/iterable.dart:490:7)\\n#1      _FirstFinder.filter (package:flutter_test/src/finders.dart:477:28)\\n#2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)\\n#3      ExpandIterator.moveNext (dart:_internal/iterable.dart:477:21)\\n#4      SetMixin.addAll (dart:collection/set.dart:57:23)\\n#5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:111:27)\\n#6      Iterable.toSet (dart:core/iterable.dart:398:21)\\n#7      _DescendantFinder.allCandidates (package:flutter_test/src/finders.dart:731:7)\\n#8      Finder.evaluate (package:flutter_test/src/finders.dart:391:61)\\n#9      WidgetController.state (package:flutter_test/src/controller.dart:156:31)\\n#10     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1027:42)\\n#11     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1026:39)\\n#14     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#15     WidgetTester.showKeyboard (package:flutter_test/src/widget_tester.dart:1026:27)\\n#16     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1062:13)\\n#17     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1061:39)\\n#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#21     WidgetTester.enterText (package:flutter_test/src/widget_tester.dart:1061:27)\\n#22     main.<anonymous closure>.<anonymous closure> (file:///D:/Master%20Folder/GSU/App%20Dev/demo8/GroupChatApp/integration_test/app_test.dart:29:20)\\n<asynchronous suspension>\\n#23     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:155:15)\\n<asynchronous suspension>\\n#24     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:782:5)\\n<asynchronous suspension>\\n(elided 4 frames from dart:async)\\n\\nThe test description was:\\n  full app test\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:29:15.472409 >>> {command: get_health}
2021-07-09 04:29:16.369045 <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:29:16.426037 >>> {command: request_data, timeout: 1200000}
2021-07-09 04:29:24.856127 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"full app test\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following StateError was thrown running a test:\\nBad state: No element\\n\\nWhen the exception was thrown, this was the stack:\\n#0      Iterable.first (dart:core/iterable.dart:490:7)\\n#1      _FirstFinder.filter (package:flutter_test/src/finders.dart:477:28)\\n#2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)\\n#3      ExpandIterator.moveNext (dart:_internal/iterable.dart:477:21)\\n#4      SetMixin.addAll (dart:collection/set.dart:57:23)\\n#5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:111:27)\\n#6      Iterable.toSet (dart:core/iterable.dart:398:21)\\n#7      _DescendantFinder.allCandidates (package:flutter_test/src/finders.dart:731:7)\\n#8      Finder.evaluate (package:flutter_test/src/finders.dart:391:61)\\n#9      WidgetController.state (package:flutter_test/src/controller.dart:156:31)\\n#10     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1027:42)\\n#11     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1026:39)\\n#14     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#15     WidgetTester.showKeyboard (package:flutter_test/src/widget_tester.dart:1026:27)\\n#16     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1062:13)\\n#17     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1061:39)\\n#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#21     WidgetTester.enterText (package:flutter_test/src/widget_tester.dart:1061:27)\\n#22     main.<anonymous closure>.<anonymous closure> (file:///D:/Master%20Folder/GSU/App%20Dev/demo8/GroupChatApp/integration_test/app_test.dart:29:20)\\n<asynchronous suspension>\\n#23     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:155:15)\\n<asynchronous suspension>\\n#24     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:782:5)\\n<asynchronous suspension>\\n(elided 4 frames from dart:async)\\n\\nThe test description was:\\n  full app test\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:31:07.285090 >>> {command: get_health}
2021-07-09 04:31:07.491643 <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:31:07.684646 >>> {command: request_data, timeout: 1200000}
2021-07-09 04:31:16.095103 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"full app test\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following StateError was thrown running a test:\\nBad state: No element\\n\\nWhen the exception was thrown, this was the stack:\\n#0      Iterable.first (dart:core/iterable.dart:490:7)\\n#1      _FirstFinder.filter (package:flutter_test/src/finders.dart:477:28)\\n#2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)\\n#3      ExpandIterator.moveNext (dart:_internal/iterable.dart:477:21)\\n#4      SetMixin.addAll (dart:collection/set.dart:57:23)\\n#5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:111:27)\\n#6      Iterable.toSet (dart:core/iterable.dart:398:21)\\n#7      _DescendantFinder.allCandidates (package:flutter_test/src/finders.dart:731:7)\\n#8      Finder.evaluate (package:flutter_test/src/finders.dart:391:61)\\n#9      WidgetController.state (package:flutter_test/src/controller.dart:156:31)\\n#10     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1027:42)\\n#11     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1026:39)\\n#14     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#15     WidgetTester.showKeyboard (package:flutter_test/src/widget_tester.dart:1026:27)\\n#16     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1062:13)\\n#17     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1061:39)\\n#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#21     WidgetTester.enterText (package:flutter_test/src/widget_tester.dart:1061:27)\\n#22     main.<anonymous closure>.<anonymous closure> (file:///D:/Master%20Folder/GSU/App%20Dev/demo8/GroupChatApp/integration_test/app_test.dart:29:20)\\n<asynchronous suspension>\\n#23     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:155:15)\\n<asynchronous suspension>\\n#24     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:782:5)\\n<asynchronous suspension>\\n(elided 4 frames from dart:async)\\n\\nThe test description was:\\n  full app test\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:32:17.555239 >>> {command: get_health}
2021-07-09 04:32:17.959760 <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:32:18.072763 >>> {command: request_data, timeout: 1200000}
2021-07-09 04:32:26.423693 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"full app test\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following StateError was thrown running a test:\\nBad state: No element\\n\\nWhen the exception was thrown, this was the stack:\\n#0      Iterable.first (dart:core/iterable.dart:490:7)\\n#1      _FirstFinder.filter (package:flutter_test/src/finders.dart:477:28)\\n#2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)\\n#3      ExpandIterator.moveNext (dart:_internal/iterable.dart:477:21)\\n#4      SetMixin.addAll (dart:collection/set.dart:57:23)\\n#5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:111:27)\\n#6      Iterable.toSet (dart:core/iterable.dart:398:21)\\n#7      _DescendantFinder.allCandidates (package:flutter_test/src/finders.dart:731:7)\\n#8      Finder.evaluate (package:flutter_test/src/finders.dart:391:61)\\n#9      WidgetController.state (package:flutter_test/src/controller.dart:156:31)\\n#10     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1027:42)\\n#11     WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1026:39)\\n#14     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#15     WidgetTester.showKeyboard (package:flutter_test/src/widget_tester.dart:1026:27)\\n#16     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1062:13)\\n#17     WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1061:39)\\n#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\\n#21     WidgetTester.enterText (package:flutter_test/src/widget_tester.dart:1061:27)\\n#22     main.<anonymous closure>.<anonymous closure> (file:///D:/Master%20Folder/GSU/App%20Dev/demo8/GroupChatApp/integration_test/app_test.dart:29:20)\\n<asynchronous suspension>\\n#23     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:155:15)\\n<asynchronous suspension>\\n#24     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:782:5)\\n<asynchronous suspension>\\n(elided 4 frames from dart:async)\\n\\nThe test description was:\\n  full app test\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:36:13.007766 >>> {command: get_health}
2021-07-09 04:36:13.852858 <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:36:13.920857 >>> {command: request_data, timeout: 1200000}
2021-07-09 04:36:22.470413 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:53:17.105840 >>> {command: get_health}
2021-07-09 04:53:17.903536 <<< {isError: false, response: {status: ok}, type: _extensionType, method: ext.flutter.driver}
2021-07-09 04:53:18.028535 >>> {command: request_data, timeout: 1200000}
2021-07-09 04:53:31.763925 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}, type: _extensionType, method: ext.flutter.driver}
